"/** @odoo-module **/",
"\t",
"import { registry } from '@web/core/registry';",
"const { Component, useState, xml, useService } = owl;",
"\t",
"export class $1 extends Component {",
"\tsetup(){",
"\t\tthis.state = useState({});",
"\t}",
"}",
"\t",
"$1.template = '$2'",
"registry.category('${3|fields,views,actions,effects,formatters,main_components,parsers,systray,user_menuitems|}').add('${4:name_template}', $1);"
